name: Scheduled API Trigger

on:
  workflow_dispatch:   # ← 加這一行
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 9 * * *'
    - cron: '0 13 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: |
          curl -X POST https://billtracker-cursor.onrender.com/trigger
